
#Title: Provider
#Creates tables used in the project


import ProviderDatabase 
import psycopg2


#create initial tables

def main():
	data  =  '''CREATE TABLE data (KEY VARCHAR(50) PRIMARY KEY  NOT NULL, NAME VARCHAR(100), PASTE_TIMESTAMP VARCHAR(100), DOWNLOAD_TIMESTAMP VARCHAR(100), SHA256 VARCHAR(256), MD5 VARCHAR(32), FUZZYHASH VARCHAR(256), RAWDATA TEXT); '''
	ip  =  '''CREATE TABLE ip (KEY VARCHAR(50) PRIMARY KEY  NOT NULL, NAME VARCHAR(100), PASTE_TIMESTAMP VARCHAR(100), DOWNLOAD_TIMESTAMP VARCHAR(100), IP VARCHAR(50)); '''
	powershell  =  '''CREATE TABLE powershell (KEY VARCHAR(50) PRIMARY KEY  NOT NULL, NAME VARCHAR(100), PASTE_TIMESTAMP VARCHAR(100), DOWNLOAD_TIMESTAMP VARCHAR(100), SHA256 VARCHAR(256), MD5 VARCHAR(32), FUZZYHASH VARCHAR(256), RAWDATA TEXT,  CLAM_AV TEXT); '''
	execs  =  '''CREATE TABLE execs (KEY VARCHAR(50) PRIMARY KEY  NOT NULL, NAME VARCHAR(100), PASTE_TIMESTAMP VARCHAR(100), DOWNLOAD_TIMESTAMP VARCHAR(100), SHA256 VARCHAR(256), MD5 VARCHAR(32), FUZZYHASH VARCHAR(256), RAWDATA TEXT, TYPE VARCHAR(256) , CLAM_AV TEXT); '''
	hashdump  =  '''CREATE TABLE hashdump (KEY VARCHAR(50) PRIMARY KEY  NOT NULL, NAME VARCHAR(100), PASTE_TIMESTAMP VARCHAR(100), DOWNLOAD_TIMESTAMP VARCHAR(100), SHA256 VARCHAR(256), MD5 VARCHAR(32), FUZZYHASH VARCHAR(256), RAWDATA TEXT, TYPE VARCHAR(100)); '''
	creds  =  '''CREATE TABLE creds (KEY VARCHAR(50) PRIMARY KEY  NOT NULL, NAME VARCHAR(100), PASTE_TIMESTAMP VARCHAR(100), DOWNLOAD_TIMESTAMP VARCHAR(100), SHA256 VARCHAR(256), MD5 VARCHAR(32), FUZZYHASH VARCHAR(256), RAWDATA TEXT,  TYPE VARCHAR(100)); '''
	domains  =  '''CREATE TABLE domains (KEY VARCHAR(50) PRIMARY KEY  NOT NULL, NAME VARCHAR(100), PASTE_TIMESTAMP VARCHAR(100), DOWNLOAD_TIMESTAMP VARCHAR(100), SHA256 VARCHAR(256), MD5 VARCHAR(32), FUZZYHASH VARCHAR(256), RAWDATA TEXT); '''
	base64  =  '''CREATE TABLE base64 (KEY VARCHAR(50) PRIMARY KEY  NOT NULL, NAME VARCHAR(100), PASTE_TIMESTAMP VARCHAR(100), DOWNLOAD_TIMESTAMP VARCHAR(100), SHA256 VARCHAR(256), MD5 VARCHAR(32), FUZZYHASH VARCHAR(256), RAWDATA TEXT, CLAMAV TEXT, TYPE VARCHAR(100)); '''


	create_table(data)
	create_table(ip)
	create_table(powershell)
	create_table(execs)
	create_table(hashdump)
	create_table(creds)
	create_table(domains)
	create_table(base64)

def create_table(str):
	connection, cursor = ProviderDatabase.get_connection()
	try:
		cursor.execute(str)
		connection.commit()
	except (Exception,  psycopg2.DatabaseError) as error :
		if "already exists" in error:
			pass
		else:
			print error

	if(connection):
		cursor.close()
		connection.close()


if __name__ == "__main__":
	main()






